# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a4ac2dd4432a8dafd0b78e3c29313d6a6f4ac673d4b83a1def4476b299cbcc77d77af6127a273d2b0a8d7bb160e539420772ae4393f901276f60505a3156435b

test:
  secret_key_base: 1065dab20af18a79dc71beb9653a24a5c58d2194c7791e167784beb488dcc5fdc2bf1e7de2faaa36b33ad9ecaa0e5e9bb344f417da9b78b23d07f4339d3b4659

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
